function configure_submission_figures
% Force journal-safe colors independently of the desktop theme.

set(groot, ...
    'defaultFigureColor','w', ...
    'defaultAxesColor','w', ...
    'defaultAxesXColor','k', ...
    'defaultAxesYColor','k', ...
    'defaultAxesZColor','k', ...
    'defaultTextColor','k', ...
    'defaultLegendColor','w', ...
    'defaultLegendTextColor','k', ...
    'defaultColorbarColor','k')
end
